# Generated by Django 2.1.3 on 2019-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190625_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Attachimage',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
