# Generated by Django 2.1.3 on 2019-06-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190625_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='AttachFileName',
        ),
    ]
