# Generated by Django 2.1.3 on 2019-06-25 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

   